### ISSUE TITLE
Theme backport

### ISSUE THREAD

**Issue by solbjorn** [shimmerproject/libreoffice-style-elementary#2]
Hi there! New icon theme for LOffice is awesome, do you have any plans for backporting it to Trusty repositories after Werewolf release or it will be available in only through PPA on 14.04?

**Comment by ochosi** [comment]
Currently the icon-theme supports LO 5.0 so while we could set up a build for 14.04 I'm not sure how well it would work and I'd rather not get bugreports about that...

**Comment by solbjorn** [comment]
@ochosi Should it work on LO 4.x? Once i had installed it on 14.04 with LOffice 4.2 and could not even select it in options. If you want, i can test it one more and make an issue for this with more details.

**Comment by ochosi** [comment]
That's exactly my point, I have no clue whether it works on LO 4.x since that was not our development focus. It could work and if it does, it should be fairly trivial to copy the existing package in the PPA over to 14.04.

I'd say download the existing package from the PPA manually and install it by hand in 14.04 and see whether it works. If it does, we can copy the package and make it available for 14.04.

**Comment by solbjorn** [comment]
No, this theme doesn't wok in LO 4.x. (tried on 14.04, package from shimmer-daily PPA) and, considering it, i think, this issue is incorrect (cause LO 5.0 isn't officially available in current LTS) and I'm closing it. Will see it in 16.04 LTS.
