### ISSUE TITLE
How to install this style?

### ISSUE THREAD

**Issue by fer-ri** [shimmerproject/libreoffice-style-elementary#3]
Please put how to install on readme.md :+1: 

Thanks

**Comment by ochosi** [comment]
Hey!
This repo will be closed shortly because the theme has been merged upstream (see http://cgit.freedesktop.org/libreoffice/core/tree/icon-themes), so all future updates/contributions will happen in the LibreOffice git, not here. This also means that it will be distributed with LibreOffice so whatever way you get LibreOffice itself should also provide you with the theme.
Thanks for your interest though - feel free to get in touch if you want to contribute!

**Comment by fer-ri** [comment]
Thanks for your info :+1:
